### ISSUE TITLE
Mapping transformer to increment number only when product changes (not when variants of same product are processed)

### ISSUE THREAD

**Issue by techlaufen** [sphereio/sphere-product-mapper#10]
Current behaviour:
For example two blue jumpers by the same manufacturer with two different sizes (represented by 201 & 202) the mapping tool increments the 6 digit number for each variant:
WDROJU100001201
WDROJU100002202

Required behaviour: 6 digit number only increments when the product type changes e.g the same 6 digit number is used for variants of the same product
WDROJU100001201
WDROJU100001202

**Comment by svenmueller** [comment]
@techlaufen Please have a look at the value transformer called `oncePerGroup` (see [README.md](https://github.com/sphereio/sphere-product-mapper#value-transformers)). Is that what you need maybe?

**Comment by OlegIlyenko** [comment]
@techlaufen, @svenmueller is correct. I implemented [oncePerGroup](https://github.com/sphereio/sphere-product-mapper#value-transformers) value transformer to sutisfy this requirement. So you can just can wrap `sphereSequence` in this one and it should works as you described.

**Comment by OlegIlyenko** [comment]
Sorry, looks like the current implementation of `oncePerGroup` will not work correctly in combination with `repeatOnDuplicateSku`, so I reopened this issue. I will reimplement it as soon as possible.

**Comment by OlegIlyenko** [comment]
`oncePerGroup` should now work correctly with `repeatOnDuplicateSku`
