### ISSUE TITLE
Provide GUI for mapper

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-product-mapper#12]
Similar to: http://impex.sphere.io/ it should be possible to run mapper without console. Many customers does not have proper setup on their machines to run it locally.

**Comment by OlegIlyenko** [comment]
CSV mapper is CLI tool, so there would be no GUI for the tool itself. We can consider to created a UI for it (or maybe some kind of web application), but it would be external to and independent from sphere-product-mapper or csv-mapper library.
