### ISSUE TITLE
Rename to sphere-csv-mapper

### ISSUE THREAD

**Issue by hajoeichler** [sphereio/sphere-product-mapper#13]
Or any more meaningful name ;)

**Comment by schleichardt** [comment]
sphere-product-csv-mapper? If it is just csv mapper I would expect it works also for categories.

**Comment by hajoeichler** [comment]
It does work with any CSV - even sphere independent.

**Comment by OlegIlyenko** [comment]
Now csv-mapper has it's own life:

https://github.com/sphereio/csv-mapper

**Comment by hajoeichler** [comment]
+1
