### ISSUE TITLE
No Error Message when using mapping tool

### ISSUE THREAD

**Issue by mitsch2000** [sphereio/sphere-product-mapper#8]
I get an empty file (only Header) and no error message when try to use a file without a sku included.

```
Michels-MacBook-Pro-2:data mitsch$ ./map-retailer-to-master.sh -p <key> -i <id> -s <secret> -r /Users/mitsch/Downloads/01\ Iphoria\ upload_0304.csv 
Michels-MacBook-Pro-2:data mitsch$ 
```

**Comment by OlegIlyenko** [comment]
Thanks for reporting. This problem should be now fixed (and you will always see the the error message now if something goes wrong)
